import { api } from './api';

function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export const isPushSupported = (): boolean => {
  return (
    typeof window !== 'undefined' &&
    'serviceWorker' in navigator &&
    'PushManager' in window &&
    'Notification' in window
  );
};

export const getNotificationPermission = (): NotificationPermission | 'unsupported' => {
  if (!isPushSupported()) return 'unsupported';
  return Notification.permission;
};

/**
 * Register Service Worker for push notifications
 */
export const registerServiceWorker = async (): Promise<ServiceWorkerRegistration | null> => {
  if (!isPushSupported()) return null;

  try {
    const registration = await navigator.serviceWorker.register('/sw.js', {
      scope: '/',
    });
    console.log('[PushService] Service Worker registered with scope:', registration.scope);
    return registration;
  } catch (error) {
    console.error('[PushService] Service Worker registration failed:', error);
    return null;
  }
};

/**
 * Check if the browser currently has an active Push Subscription
 */
export const getActiveSubscription = async (): Promise<PushSubscription | null> => {
  if (!isPushSupported()) return null;

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();
    return subscription;
  } catch (error) {
    console.error('[PushService] Error checking active push subscription:', error);
    return null;
  }
};

/**
 * Request notification permission and subscribe device to Web Push
 */
export const subscribeToPush = async (): Promise<{ success: boolean; error?: string }> => {
  if (!isPushSupported()) {
    return { success: false, error: 'Web Push is not supported in this browser.' };
  }

  try {
    // 1. Request permission from browser
    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      return {
        success: false,
        error: permission === 'denied'
          ? 'Notifications are blocked in your browser settings. Please allow notifications for this site to receive reminder alerts.'
          : 'Notification permission was not granted.',
      };
    }

    // 2. Fetch VAPID Public Key from server
    let publicKey = import.meta.env.VITE_VAPID_PUBLIC_KEY;
    if (!publicKey) {
      const res = await api.get('/push/public-key');
      publicKey = res.data.data.publicKey;
    }

    if (!publicKey) {
      return { success: false, error: 'Server VAPID public key unavailable.' };
    }

    // 3. Register service worker and subscribe with PushManager
    const registration = await navigator.serviceWorker.ready;
    let subscription = await registration.pushManager.getSubscription();

    if (!subscription) {
      const convertedVapidKey = urlBase64ToUint8Array(publicKey);
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedVapidKey as any,
      });
    }

    // 4. Send subscription to JARVIS backend
    const subJSON = subscription.toJSON();
    if (!subJSON.endpoint || !subJSON.keys) {
      return { success: false, error: 'Malformed subscription object generated by browser.' };
    }

    await api.post('/push/subscribe', {
      subscription: {
        endpoint: subJSON.endpoint,
        keys: {
          p256dh: subJSON.keys.p256dh,
          auth: subJSON.keys.auth,
        },
      },
      userAgent: navigator.userAgent,
    });

    console.log('[PushService] Successfully subscribed to Web Push.');
    return { success: true };
  } catch (error: any) {
    console.error('[PushService] Failed to subscribe to Web Push:', error);
    return {
      success: false,
      error: error.response?.data?.error?.message || error.message || 'Failed to enable Web Push notifications.',
    };
  }
};

/**
 * Unsubscribe current browser from Web Push
 */
export const unsubscribeFromPush = async (): Promise<{ success: boolean; error?: string }> => {
  if (!isPushSupported()) {
    return { success: false, error: 'Web Push is not supported in this browser.' };
  }

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();

    if (subscription) {
      const endpoint = subscription.endpoint;
      await subscription.unsubscribe();

      // Tell backend to remove record
      await api.post('/push/unsubscribe', { endpoint }).catch((err) => {
        console.warn('[PushService] Server unsubscribe sync warning:', err);
      });
    }

    console.log('[PushService] Successfully unsubscribed from Web Push.');
    return { success: true };
  } catch (error: any) {
    console.error('[PushService] Failed to unsubscribe from Web Push:', error);
    return { success: false, error: error.message || 'Failed to disable notifications.' };
  }
};

/**
 * Trigger an immediate test push from the backend to verify device alerts
 */
export const triggerTestPush = async (): Promise<{ success: boolean; error?: string }> => {
  try {
    await api.post('/push/test');
    return { success: true };
  } catch (error: any) {
    return {
      success: false,
      error: error.response?.data?.error?.message || error.message || 'Failed to trigger test push.',
    };
  }
};
